---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.6에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.6의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.6에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다.

최신 버전의 Cloud Manager에는 추가 기능과 개선 사항도 포함되어 있습니다. 를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager 릴리즈 노트"^] 를 참조하십시오.



== 9.6 P8(2020년 6월 2일)

Cloud Volumes ONTAP용 9.6 P8 패치 릴리스는 현재 Cloud Manager 3.8 이상을 통해 제공됩니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P8["P8 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.6 P7(2020년 4월 8일)

Cloud Volumes ONTAP용 9.6 P7 패치 릴리스는 현재 Cloud Manager 3.8 이상을 통해 제공됩니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P7["P7 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.6 P6(2020년 3월 6일)

Cloud Volumes ONTAP용 9.6 P6 패치 릴리스는 현재 Cloud Manager 3.8 이상에서 사용할 수 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P6["P6 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== AWS 업데이트(2020년 2월 16일)

NetApp은 새로운 EC2 인스턴스에 대한 지원과 지원되는 데이터 디스크 수의 변경을 발표했습니다.



=== 새 인스턴스 지원

프리미엄 또는 BYOL 라이센스를 사용하는 경우, 몇 가지 새로운 EC2 인스턴스 유형이 Cloud Volumes ONTAP 9.6에서 지원됩니다.

* c5.9xLarge
* c5d.18xLarge^1,2^
* m5d.8xLarge^1,2^


^1^ 이러한 인스턴스 유형에는 Cloud Volumes ONTAP이 _Flash Cache_로 사용하는 로컬 NVMe 스토리지가 포함됩니다. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["자세한 정보"^].

^2^ 이러한 인스턴스 유형은 9.6 P3 이상에서 지원됩니다.

https://aws.amazon.com/ec2/instance-types/["이러한 EC2 인스턴스 유형에 대해 자세히 알아보십시오"^].

link:reference-configs-aws.html["AWS에서 지원되는 9.6 구성에 대해 자세히 알아보십시오"].



=== 지원되는 데이터 디스크

이제 C5, M5 및 R5 인스턴스에 대해 데이터 디스크 하나를 적게 지원합니다. 단일 노드 시스템의 경우 22개의 데이터 디스크가 지원됩니다. HA 쌍의 경우 노드당 19개의 데이터 디스크가 지원됩니다.

link:reference-limits-aws.html["AWS의 스토리지 제한에 대해 자세히 알아보십시오"].



== Azure의 DS15_v2 지원(2020년 2월 12일)

이제 Cloud Volumes ONTAP는 단일 노드 시스템과 HA 쌍 모두에서 Azure의 DS15_v2 가상 머신 유형으로 지원됩니다.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["DSv2 시리즈에 대해 자세히 알아보십시오"^].

link:reference-configs-azure.html["Azure에서 지원되는 9.6 구성에 대해 자세히 알아보십시오"].



== 9.6 P5(2019년 12월 26일)

Cloud Volumes ONTAP용 9.6 P5 패치 릴리즈가 현재 클라우드 관리자를 통해 제공되고 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P5["P5 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.6 P4(2019년 11월 14일)

Cloud Volumes ONTAP용 9.6 P4 패치 릴리스는 현재 Cloud Manager를 통해 제공되고 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P4["P4 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.6 P3(2019년 10월 23일)

Cloud Volumes ONTAP용 9.6 P3 패치 릴리즈가 현재 클라우드 관리자를 통해 제공되고 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P3["P3 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).

버그 수정 외에도 이 릴리즈에서는 다음과 같은 기능도 지원합니다.

* AWS에서 c5.18xLarge 인스턴스 유형 지원.
* Azure에서 단일 노드 시스템의 최대 애그리게이트 크기: 352TB의 물리적 용량이 지원됩니다.
+
단일 노드 시스템의 최대 애그리게이트 크기는 이전에 200TB였습니다.





== Google Cloud Marketplace에서 용량제 구독(2019년 10월 6일)

이제 Google 클라우드 플랫폼 마켓플레이스의 Cloud Volumes ONTAP에 가입하면 Cloud Volumes ONTAP를 사용한 만큼만 비용을 지불할 수 있습니다.

https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?q=NetApp&id=8108721b-10e5-48be-88ed-387031dae492["Google Cloud Platform 마켓플레이스: Cloud Volumes ONTAP용 Cloud Manager"^]



== Google Cloud에서 Cloud Volumes ONTAP의 일반 가용성(2019년 9월 3일)

BYOL(Google Cloud Platform)로 기존 라이센스를 도입할 때 Cloud Volumes ONTAP를 Google Cloud Platform에서 사용할 수 있습니다. 선불 종량제 프로모션도 사용할 수 있습니다. 이 프로모션은 무제한 수의 시스템에 대해 무료 라이센스를 제공하며 2019년 9월 말에 만료됩니다.

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Google Cloud를 시작하는 방법을 알아보십시오"^]
* link:reference-configs-gcp.html["지원되는 구성을 봅니다"]




== 9.6 P2(2019년 8월 29일)

Cloud Volumes ONTAP용 9.6 P2 패치 릴리즈가 현재 Cloud Manager를 통해 제공되고 있습니다. Cloud Manager에서 기존 9.5 및 9.6 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P2["P2 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.6 GA(2019년 7월 15일)

Cloud Volumes ONTAP 9.6의 GA(General Availability) 릴리스가 출시되었습니다. GA 릴리스에는 버그 수정이 포함되어 있습니다. Cloud Manager에서 기존 시스템을 이 릴리즈로 업그레이드하라는 메시지가 표시됩니다.


NOTE: Cloud Volumes ONTAP은 Google 클라우드 플랫폼에서 비공개 미리보기로 유지됩니다.



== 9.6 RC1(2019년 6월 16일)

Cloud Volumes ONTAP 9.6 RC1은 AWS, Azure 및 Google 클라우드 플랫폼에서 제공됩니다. 이 릴리스에는 다음과 같은 기능이 포함되어 있습니다.

* <<Private preview of Cloud Volumes ONTAP in Google Cloud Platform>>
* <<Data tiering with HA pairs in Azure>>
* <<Support for FlexCache volumes>>
* <<Additional ONTAP changes>>




=== Google 클라우드 플랫폼에서 Cloud Volumes ONTAP을 비공개로 미리보기

Google 클라우드 플랫폼에서 Cloud Volumes ONTAP의 비공개 미리 보기를 사용할 수 있습니다. 다른 클라우드 공급자와 마찬가지로, Google Cloud Platform용 Cloud Volumes ONTAP를 사용하면 비용을 절감하고 성능을 높이며 가용성을 높일 수 있습니다.

Cloud Volumes ONTAP는 Google Cloud에서 단일 노드 시스템으로 제공되며 오브젝트 스토리지에 대한 데이터 계층화를 지원합니다.

비공개 미리 보기에 참가하려면 ng-Cloud-Volume-ONTAP-preview@netapp.com 으로 요청을 보냅니다.



=== Azure의 HA 쌍을 통한 데이터 계층화

이제 Microsoft Azure의 Cloud Volumes ONTAP HA 쌍에서 데이터 계층화가 지원됩니다. 데이터 계층화를 통해 비활성 데이터를 저비용 Blob 스토리지로 자동 계층화할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-tiering.html["Cloud Manager에서 데이터 계층화를 설정하는 방법에 대해 알아보십시오"^].



=== FlexCache 볼륨 지원

FlexCache 볼륨은 원본(또는 소스) 볼륨의 NFS 읽기 데이터를 캐싱하는 스토리지 볼륨입니다. 이후에 캐싱된 데이터를 읽으면 해당 데이터에 더 빠르게 액세스할 수 있습니다.

FlexCache 볼륨을 사용하면 데이터 액세스 속도를 높이거나 자주 액세스하는 볼륨에서 트래픽을 오프로드할 수 있습니다. FlexCache 볼륨은 원본 볼륨에 액세스하지 않고도 직접 데이터를 제공할 수 있으므로 클라이언트가 동일한 데이터에 반복적으로 액세스해야 할 때 성능을 개선할 수 있습니다. FlexCache 볼륨은 읽기 집약적인 시스템 워크로드에 적합합니다.

Cloud Manager에서는 현재 FlexCache 볼륨을 관리할 수 없지만 ONTAP CLI 또는 ONTAP System Manager를 사용하여 FlexCache 볼륨을 생성하고 관리할 수 있습니다.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["빠른 데이터 액세스를 위한 FlexCache 볼륨 전원 가이드"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["System Manager에서 FlexCache 볼륨 생성"^]


3.7.2 릴리스부터는 Cloud Manager에서 모든 새 Cloud Volumes ONTAP 시스템에 대한 FlexCache 라이센스를 생성합니다. 이 라이센스에는 500GiB 사용 제한이 포함됩니다.



=== 추가 ONTAP 변경 사항

ONTAP 9.6에는 Cloud Volumes ONTAP 사용자가 관심을 가질 수 있는 기타 변경 사항이 포함되어 있습니다.

* 이제 SnapMirror 복제는 전송 중인 통신을 위한 TLS 1.2 암호화를 지원합니다
* FabricPool(데이터 계층화)의 향상된 기능은 다음과 같습니다.
+
** 콜드 데이터를 재계층화할 필요 없이 볼륨 이동 지원
** SVM 재해 복구 지원




9.6 릴리스에 대한 자세한 내용은 을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 릴리즈 노트"^].



== 노트 업그레이드

* Cloud Volumes ONTAP 업그레이드는 Cloud Manager에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.
* 9.5 릴리스에서 Cloud Volumes ONTAP 9.6으로 업그레이드할 수 있습니다.
* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.

